### ISSUE TITLE
Incorrect type of string with example in schema

### ISSUE THREAD

**Issue by ApaDoctor** [RonnyPfannschmidt/prance#33]
In YAML you can write strings without quotes. For some specific cases you are forced to use quotes, for example when you put digits, but you want them to be of type string.
But when you write schema and set type of variable to string - when you provide `example` you expect that it will also be of type string. But it's converted to the python as integer.
## Expected Behaviour
Some schema in `requestBody` for example:
```yml
  type: object
      properties:
          some_variable:
             type: string
             example: 1111111111 # This should be string
      required: true
```
This should be:
```python
{'some_variable':'1111111111'}
```

## Actual Behaviour
```yml
  type: object
      properties:
          some_variable:
             type: string
             example: 1111111111
      required: true
```
Result:
```python
{'some_variable': 1111111111}
```
@jfinkhaeuser
